INSERT INTO proyecto1k.caja (direccion,numero) VALUES ('Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador',1);
INSERT INTO proyecto1k.caja (direccion,numero) VALUES ('Av. Talara, Cercado de Lima 15836',2);
INSERT INTO proyecto1k.caja (direccion,numero) VALUES ('Av. Talara, Cercado de Lima 15836',3);
INSERT INTO proyecto1k.caja (direccion,numero) VALUES ('Av. Talara, Cercado de Lima 15836',4);
INSERT INTO proyecto1k.caja (direccion,numero) VALUES ('Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador',5);
INSERT INTO proyecto1k.caja (direccion,numero) VALUES ('Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador',6);
INSERT INTO proyecto1k.caja (direccion,numero) VALUES ('Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador',7);
INSERT INTO proyecto1k.caja (direccion,numero) VALUES ('Av. Talara, Cercado de Lima 15836',8);
INSERT INTO proyecto1k.caja (direccion,numero) VALUES ('Av. Talara, Cercado de Lima 15836',9);
INSERT INTO proyecto1k.caja (direccion,numero) VALUES ('Av. Talara, Cercado de Lima 15836',10);