INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (1,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (3,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (4,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (8,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (9,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (10,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (11,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (13,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (14,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (15,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (16,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (19,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (21,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (22,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (23,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (24,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (27,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (28,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (29,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (32,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (33,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (35,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (36,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (38,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (39,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (42,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (43,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (46,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (48,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (50,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (52,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (56,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (57,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (59,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (60,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (61,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (63,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (64,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (65,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (66,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (67,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (69,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (70,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (71,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (72,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (73,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (74,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (75,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (76,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (78,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (80,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (81,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (83,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (84,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (85,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (87,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (90,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (91,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (92,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (95,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (96,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (97,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (99,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (100,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (101,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (103,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (104,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (105,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (106,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (108,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (109,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (111,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (112,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (113,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (114,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (115,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (116,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (118,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (120,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (121,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (122,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (125,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (126,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (127,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (128,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (129,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (131,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (133,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (135,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (139,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (140,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (144,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (147,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (149,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (150,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (152,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (153,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (154,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (160,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (162,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (165,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (166,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (167,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (170,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (172,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (173,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (174,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (177,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (178,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (179,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (180,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (183,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (184,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (185,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (186,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (188,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (191,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (193,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (198,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (199,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (200,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (201,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (207,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (208,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (209,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (210,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (212,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (213,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (214,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (215,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (216,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (218,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (219,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (221,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (222,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (224,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (225,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (226,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (227,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (228,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (231,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (232,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (233,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (234,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (237,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (240,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (241,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (242,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (244,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (247,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (251,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (252,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (253,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (254,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (256,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (257,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (258,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (261,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (262,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (263,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (264,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (266,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (267,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (268,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (269,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (271,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (272,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (274,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (277,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (278,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (280,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (281,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (283,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (285,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (286,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (288,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (290,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (293,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (294,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (295,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (296,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (299,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (301,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (302,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (304,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (305,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (309,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (310,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (311,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (314,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (319,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (323,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (324,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (326,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (330,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (331,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (332,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (333,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (335,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (336,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (337,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (339,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (340,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (342,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (343,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (344,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (345,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (346,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (349,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (350,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (351,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (352,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (353,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (354,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (356,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (358,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (362,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (552,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (364,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (366,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (369,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (370,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (371,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (372,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (373,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (375,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (376,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (377,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (378,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (379,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (381,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (384,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (386,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (390,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (392,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (396,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (397,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (398,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (401,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (403,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (404,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (406,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (407,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (408,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (410,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (412,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (414,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (416,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (417,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (418,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (419,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (420,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (422,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (423,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (424,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (425,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (427,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (429,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (432,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (433,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (434,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (435,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (437,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (438,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (440,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (441,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (442,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (443,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (444,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (445,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (451,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (452,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (454,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (456,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (458,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (460,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (461,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (464,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (465,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (466,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (470,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (471,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (472,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (473,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (474,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (476,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (477,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (478,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (480,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (483,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (484,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (486,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (488,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (490,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (492,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (493,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (494,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (495,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (496,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (497,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (499,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (500,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (502,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (503,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (505,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (506,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (513,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (515,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (516,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (518,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (521,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (522,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (523,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (524,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (525,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (526,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (527,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (528,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (530,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (531,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (532,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (534,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (535,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (538,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (540,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (541,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (544,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (546,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (553,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (554,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (555,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (557,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (559,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (560,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (561,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (563,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (565,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (567,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (569,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (570,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (571,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (572,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (575,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (576,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (577,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (578,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (579,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (581,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (582,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (585,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (586,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (588,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (589,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (591,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (592,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (593,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (595,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (597,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (598,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (600,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (603,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (604,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (606,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (608,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (610,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (613,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (614,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (618,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (621,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (622,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (623,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (624,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (625,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (627,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (628,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (630,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (631,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (632,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (634,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (636,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (637,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (640,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (643,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (644,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (645,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (647,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (648,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (650,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (651,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (653,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (656,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (657,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (659,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (661,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (663,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (665,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (666,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (667,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (668,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (669,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (672,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (673,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (674,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (675,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (676,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (677,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (678,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (680,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (681,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (682,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (683,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (684,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (685,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (686,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (687,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (688,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (689,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (691,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (692,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (693,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (694,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (697,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (699,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (702,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (703,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (706,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (708,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (711,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (712,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (715,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (718,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (720,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (721,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (722,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (723,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (724,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (725,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (726,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (729,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (730,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (731,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (733,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (735,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (738,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (739,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (740,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (741,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (743,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (746,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (752,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (753,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (754,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (755,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (757,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (758,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (759,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (760,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (761,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (762,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (763,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (764,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (767,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (770,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (773,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (774,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (775,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (776,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (777,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (780,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (782,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (784,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (785,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (787,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (788,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (791,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (794,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (796,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (797,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (801,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (802,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (803,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (804,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (805,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (807,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (808,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (812,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (816,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (819,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (820,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (821,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (824,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (828,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (830,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (831,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (832,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (833,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (834,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (835,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (839,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (841,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (842,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (844,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (846,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (847,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (849,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (850,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (852,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (853,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (858,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (859,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (860,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (862,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (863,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (864,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (865,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (866,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (867,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (868,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (870,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (871,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (873,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (874,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (875,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (877,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (878,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (880,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (882,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (883,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (884,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (885,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (886,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (887,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (891,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (892,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (893,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (894,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (895,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (896,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (897,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (899,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (900,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (902,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (903,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (904,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (905,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (906,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (907,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (908,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (909,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (911,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (912,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (913,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (914,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (916,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (917,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (919,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (920,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (921,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (922,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (923,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (924,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (925,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (928,5,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (929,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (932,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (935,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (939,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (940,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (942,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (943,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (944,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (950,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (951,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (952,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (953,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (956,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (957,9,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (958,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (959,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (961,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (962,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (964,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (965,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (970,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (971,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (973,4,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (974,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (975,2,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (978,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (981,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (982,10,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (984,6,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (985,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (989,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (990,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (992,1,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (994,3,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (996,7,'Sector 3 Grupo 23 Mz. I Lt. 23, Villa EL Salvador');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (997,8,'Av. Talara, Cercado de Lima 15836');
INSERT INTO proyecto1k.compralocal (correlativo,numero,direccion) VALUES (999,2,'Av. Talara, Cercado de Lima 15836');